name: Packages

on:
  pull_request:
    paths:
    - 'packages/**'
  push:
    branches:
    - master
    paths:
    - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: "/opt/termux/android-sdk"
      NDK: "/opt/termux/android-ndk"
    strategy:
      matrix:
        target_arch: [aarch64, arm, i686, x86_64]
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1000
    - name: Free additional disk space on host
      run: |
        sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php)') \
          liblldb-6.0 libllvm6.0:amd64 mono-runtime-common monodoc-manual ruby
        sudo apt autoremove -yq
        sudo rm -rf /usr/local
    - name: Build packages
      run: |
        BASE_COMMIT=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH")
        OLD_COMMIT=$(jq --raw-output .commits[0].id "$GITHUB_EVENT_PATH")
        HEAD_COMMIT=$(jq --raw-output .commits[-1].id "$GITHUB_EVENT_PATH")
        if [ "$BASE_COMMIT" = "null" ]; then
          if [ "$OLD_COMMIT" = "$HEAD_COMMIT" ]; then
            # Single-commit push.
            echo "Processing commit: ${HEAD_COMMIT}"
            CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "${HEAD_COMMIT}")
          else
            # Multi-commit push.
            OLD_COMMIT="${OLD_COMMIT}~1"
            echo "Processing commit range: ${OLD_COMMIT}..${HEAD_COMMIT}"
            CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "${OLD_COMMIT}" "${HEAD_COMMIT}")
          fi
        else
          # Pull requests.
          echo "Processing pull request #$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH"): ${BASE_COMMIT}..HEAD"
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "${BASE_COMMIT}" "HEAD")
        fi
        # Process tag '%ci:no-build' that may be added as line to commit message.
        # Forces CI to cancel current build with status 'passed'.
        if grep -qiP '^\s*%ci:no-build\s*$' <(git log --format="%B" -n 1 "HEAD"); then
          echo "[!] Force exiting as tag '%ci:no-build' was applied to HEAD commit message."
          exit 0
        fi
        # Remove duplicates and deleted packages from $PACKAGE_NAMES.
        PACKAGE_NAMES=$(sed -nE 's@^packages/([^/]*)/([^/]*)(/.*)?$@\1@p' <<< "$CHANGED_FILES" | sort | uniq)
        DELETED_PACKAGE_NAMES=""
        for pkg in $PACKAGE_NAMES; do
          if [ ! -d "./packages/${pkg}" ]; then
            PACKAGE_NAMES=$(sed -E "s/(^|\s\s*)${pkg}(\$|\s\s*)/ /g" <<< "$PACKAGE_NAMES")
            DELETED_PACKAGE_NAMES+=" $pkg"
          fi
        done
        # Remove trailing spaces.
        PACKAGE_NAMES=$(sed 's/[[:blank:]]*$//' <<< "$PACKAGE_NAMES")
        DELETED_PACKAGE_NAMES=$(sed 's/[[:blank:]]*$//' <<< "$DELETED_PACKAGE_NAMES")
        # Build packages.
        if [ -n "$PACKAGE_NAMES" ]; then
          ./scripts/lint-packages.sh $(echo "$PACKAGE_NAMES" | grep -P '^[a-zA-Z0-9]' | awk '{ print "./packages/"$0"/build.sh" }')
          ./start-builder.sh ./build-package.sh -I -a ${{ matrix.target_arch }} $PACKAGE_NAMES
        fi
        mkdir -p artifacts
        tar cf artifacts/debs-${{ matrix.target_arch }}-${{ github.sha }}.tar debs
    - name: Store *.deb files
      uses: actions/upload-artifact@v2
      with:
        name: x11-packages-${{ github.sha }}
        path: ./artifacts
  upload:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Get *.deb files
      uses: actions/download-artifact@v2
      with:
        name: x11-packages-${{ github.sha }}
        path: ./
    - name: Upload to packages.termux.org
      env:
        REPOSITORY_NAME: termux-x11
        REPOSITORY_DISTRIBUTION: x11
      run: |
        for archive in *.tar; do
          tar xf "$archive"
        done
        # TODO: handle errors instead of relying on curl exit code.
        uploaded_files=false
        for filename in debs/*.deb; do
          # Upload file to temporary directory.
          curl --fail -X POST -u "${{ secrets.APTLY_API_AUTH }}" -F file=@${filename} \
            https://packages.termux.org/aptly-api/files/${REPOSITORY_NAME}-${{ github.sha }}
          uploaded_files=true
        done
        if [ "$uploaded_files" = "true" ]; then
          # This assigns the uploaded file to given repository.
          # Temporary directory is being removed at this step.
          curl --fail -X POST -u "${{ secrets.APTLY_API_AUTH }}" \
            https://packages.termux.org/aptly-api/repos/${REPOSITORY_NAME}/file/${REPOSITORY_NAME}-${{ github.sha }}
          # This will cause Aptly to rebuild apt repository.
          curl --fail -X PUT -u "${{ secrets.APTLY_API_AUTH }}" \
            -H 'Content-Type: application/json' --data '{"Signing": {"Passphrase": "${{ secrets.GPG_PASSPHRASE }}"}}' \
            https://packages.termux.org/aptly-api/publish/${REPOSITORY_NAME}/${REPOSITORY_DISTRIBUTION}
        fi
