name: Packages

on:
  pull_request:
    paths:
    - 'packages/**'
  push:
    branches:
    - master
    paths:
    - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: "/opt/termux/android-sdk"
      NDK: "/opt/termux/android-ndk"
    strategy:
      matrix:
        target_arch: [aarch64, arm, i686, x86_64]
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1000
    - name: Free additional disk space on host
      run: |
        sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php)') \
          liblldb-6.0 libllvm6.0:amd64 mono-runtime-common monodoc-manual ruby
        sudo apt autoremove -yq
        sudo rm -rf /usr/local
    - name: Build packages
      run: |
        BASE_COMMIT=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH")
        OLD_COMMIT=$(jq --raw-output .commits[0].id "$GITHUB_EVENT_PATH")
        HEAD_COMMIT=$(jq --raw-output .commits[-1].id "$GITHUB_EVENT_PATH")
        if [ "$BASE_COMMIT" = "null" ]; then
          if [ "$OLD_COMMIT" = "$HEAD_COMMIT" ]; then
            # Single-commit push.
            echo "Processing commit: ${HEAD_COMMIT}"
            CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "${HEAD_COMMIT}")
          else
            # Multi-commit push.
            OLD_COMMIT="${OLD_COMMIT}~1"
            echo "Processing commit range: ${OLD_COMMIT}..${HEAD_COMMIT}"
            CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "${OLD_COMMIT}" "${HEAD_COMMIT}")
          fi
        else
          # Pull requests.
          echo "Processing pull request #$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH"): ${BASE_COMMIT}..HEAD"
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "${BASE_COMMIT}" "HEAD")
        fi
        # Process tag '%ci:no-build' that may be added as line to commit message.
        # Forces CI to cancel current build with status 'passed'.
        if grep -qiP '^\s*%ci:no-build\s*$' <(git log --format="%B" -n 1 "HEAD"); then
          echo "[!] Force exiting as tag '%ci:no-build' was applied to HEAD commit message."
          exit 0
        fi
        # Remove duplicates and deleted packages from $PACKAGE_NAMES.
        PACKAGE_NAMES=$(sed -nE 's@^packages/([^/]*)/([^/]*)(/.*)?$@\1@p' <<< "$CHANGED_FILES" | sort | uniq)
        DELETED_PACKAGE_NAMES=""
        for pkg in $PACKAGE_NAMES; do
          if [ ! -d "./packages/${pkg}" ]; then
            PACKAGE_NAMES=$(sed -E "s/(^|\s\s*)${pkg}(\$|\s\s*)/ /g" <<< "$PACKAGE_NAMES")
            DELETED_PACKAGE_NAMES+=" $pkg"
          fi
        done
        # Remove trailing spaces.
        PACKAGE_NAMES=$(sed 's/[[:blank:]]*$//' <<< "$PACKAGE_NAMES")
        DELETED_PACKAGE_NAMES=$(sed 's/[[:blank:]]*$//' <<< "$DELETED_PACKAGE_NAMES")
        # Build packages.
        if [ -n "$PACKAGE_NAMES" ]; then
          ./scripts/lint-packages.sh $(echo "$PACKAGE_NAMES" | grep -P '^[a-zA-Z0-9]' | awk '{ print "./packages/"$0"/build.sh" }')
          ./start-builder.sh ./build-package.sh -I -a ${{ matrix.target_arch }} $PACKAGE_NAMES
        fi
        mkdir -p artifacts
        tar cf artifacts/debs-${{ matrix.target_arch }}-${{ github.sha }}.tar debs
    - name: Store *.deb files
      uses: actions/upload-artifact@v2
      with:
        name: x11-packages-${{ github.sha }}
        path: ./artifacts
  upload:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Get *.deb files
      uses: actions/download-artifact@v2
      with:
        name: x11-packages-${{ github.sha }}
        path: ./
    - name: Upload to packages.termux.org
      env:
        REPOSITORY_NAME: termux-x11
        REPOSITORY_DISTRIBUTION: x11
      run: |
        for archive in *.tar; do
          tar xf "$archive"
        done

        # Function for deleting temporary directory with uploaded files from
        # the server.
        aptly_delete_dir() {
          echo "[*] Deleting uploads temporary directory."

          curl_response=$(
            curl \
              --silent \
              --user "${{ secrets.APTLY_API_AUTH }}" \
              --request DELETE \
              --write-out "|%{http_code}" \
              https://packages.termux.org/aptly-api/files/${REPOSITORY_NAME}-${{ github.sha }}
          )

          http_status_code=$(echo "$curl_response" | cut -d'|' -f2)

          if [ "$http_status_code" != "200" ]; then
            echo "[!] Server returned $http_status_code code while deleting temporary directory."
          fi
        }

        # Upload file to temporary directory.
        uploaded_files=false
        for filename in debs/*.deb; do
          curl_response=$(
            curl \
              --silent \
              --user "${{ secrets.APTLY_API_AUTH }}" \
              --request POST \
              --form file=@${filename} \
              --write-out "|%{http_code}" \
              https://packages.termux.org/aptly-api/files/${REPOSITORY_NAME}-${{ github.sha }}
          )

          http_status_code=$(echo "$curl_response" | cut -d'|' -f2)

          if [ "$http_status_code" = "200" ]; then
            echo "[*] Uploaded: $(echo "$curl_response" | cut -d'|' -f1 | jq -r '.[]' | cut -d'/' -f2)"
          else
            # Manually cleaning up the temporary directory to reclaim disk space.
            # Don't rely on scheduled server-side scripts.
            echo "[!] Failed to upload '$filename'. Server returned $http_status_code code."
            echo "[!] Aborting any further uploads."
            aptly_delete_dir
            exit 1
          fi

          uploaded_files=true
        done

        # Publishing repository changes.
        if [ "$uploaded_files" = "true" ]; then
          echo "[*] Adding packages to repository '$REPOSITORY_NAME'..."

          curl_response=$(
            curl \
              --silent \
              --user "${{ secrets.APTLY_API_AUTH }}" \
              --request POST \
              --write-out "|%{http_code}" \
              https://packages.termux.org/aptly-api/repos/${REPOSITORY_NAME}/file/${REPOSITORY_NAME}-${{ github.sha }}
          )

          http_status_code=$(echo "$curl_response" | cut -d'|' -f2)

          if [ "$http_status_code" = "200" ]; then
            warnings=$(echo "$curl_response" | cut -d'|' -f1 | jq '.Report.Warnings' | jq -r '.[]')
            if [ -n "$warnings" ]; then
              echo "[!] There are some warnings were returned:"
              echo
              echo "$warnings"
              echo
            fi

            # Upload directory is usually deleted automatically once all deb
            # files were added without issues. Attempting to do this manually
            # in case it left for some reason (e.g. some debs not added due to
            # conflicts).
            aptly_delete_dir
          else
            echo "[*] Server returned $http_status_code. Not publishing repository!"
            aptly_delete_dir
            exit 1
          fi

          # Final part to make changes appear in web root.
          echo "[*] Publishing repository changes..."

          curl_response=$(
            curl \
              --silent \
              --user "${{ secrets.APTLY_API_AUTH }}" \
              --header 'Content-Type: application/json' \
              --request PUT \
              --data '{"Signing": {"Passphrase": "${{ secrets.GPG_PASSPHRASE }}"}}' \
              --write-out "|%{http_code}" \
              https://packages.termux.org/aptly-api/publish/${REPOSITORY_NAME}/${REPOSITORY_DISTRIBUTION}
          )

          http_status_code=$(echo "$curl_response" | cut -d'|' -f2)

          if [ "$http_status_code" = "200" ]; then
            echo "[*] Repository updated successfully."
          else
            # Note: may return error 500 if gpg signing failed.
            echo "[*] Server returned $http_status_code."
            exit 1
          fi
        fi
